# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpa1m5C2LOar0hvexrdEZRHEwhYChav2
"""

#1. Create a NumPy array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#2. Zeros and Ones
a = np.zeros((3,3))
b = np.ones((2,4))
print(a)
print(b)

#3. Random Numbers
rand_arr = np.random.rand(3,3)
print(rand_arr)

#4. Reshape
arr = np.arange(12).reshape(3,4)
print(arr)

#5. Array Slicing
arr = np.array([10,20,30,40,50])
print(arr[1:4])

#6. Mathematical Operations
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
#7. Matrix Multiplication
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))

#8. Transpose
mat = np.array([[1,2,3],[4,5,6]])
print(mat.T)

#9. Mean, Median, Std
data = np.array([10,20,30,40,50])
print(np.mean(data))
print(np.median(data))
print(np.std(data))

#10. Sorting
arr = np.array([5,2,8,1,9])
print(np.sort(arr))

#11. Concatenate
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

#12. Unique Elements
arr = np.array([1,2,2,3,4,4,5])
print(np.unique(arr))

#13. Linspace
arr = np.linspace(0,1,5)
print(arr)

#14. Identity Matrix
print(np.eye(4))

#15. Argmax and Argmin
arr = np.array([10,50,20,5])
print(np.argmax(arr))
print(np.argmin(arr))

#16. Where Condition
arr = np.array([10,20,30,40])
print(np.where(arr>25))

#17. Cumulative Sum
arr = np.array([1,2,3,4])
print(np.cumsum(arr))

#18. Random Integers
rand_ints = np.random.randint(1,100,10)
print(rand_ints)

#10 random integers between 1 and 100

#19. Correlation Coefficient
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])
print(np.corrcoef(x,y))

#20. Save and Load NumPy Array
arr = np.array([1,2,3,4,5])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print(loaded)